version: '3.8'
services:
  mysql-interview:
    build:
      context: ./backend/mysql
      dockerfile: Dockerfile
    # image: mariadb
    restart: always
    stdin_open: true # docker run -i
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - mysql-interview-vol:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: interview
  backend-interview:
    build: ./backend
    ports:
      - '3001:3000'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql-interview
volumes:
  mysql-interview-vol:
